import type {
  Product,
  Thread,
  Message,
  Exchange,
  InventoryEvent,
  RecentActivity,
  DashboardStats,
} from '../types';

const now = Date.now();
const hour = 3600 * 1000;
const day = 24 * hour;

// ---- PRODUCTS ----

export const mockProducts: Product[] = [
  {
    _id: 'prod_1',
    type: 'phone',
    phoneType: 'iPhone 14 Pro',
    ram: '6GB',
    storage: '256GB',
    condition: 'Excellent',
    price: 95000,
    stockQuantity: 3,
    exchangeEnabled: true,
    description: 'Space Black, like new condition. Comes with original box.',
    images: [{ storageId: 'st_1', url: 'https://placehold.co/300x300/1a1a2e/ffffff?text=iPhone+14+Pro', order: 1 }],
    createdAt: now - 10 * day,
    createdBy: '123456789',
    updatedAt: now - 2 * day,
    updatedBy: '123456789',
  },
  {
    _id: 'prod_2',
    type: 'phone',
    phoneType: 'Galaxy S23 Ultra',
    ram: '12GB',
    storage: '512GB',
    condition: 'Good',
    price: 85000,
    stockQuantity: 2,
    exchangeEnabled: true,
    description: 'Phantom Black. Minor scratches on back, screen perfect.',
    images: [{ storageId: 'st_2', url: 'https://placehold.co/300x300/1a2e1a/ffffff?text=S23+Ultra', order: 1 }],
    createdAt: now - 7 * day,
    createdBy: '123456789',
    updatedAt: now - 1 * day,
    updatedBy: '123456789',
  },
  {
    _id: 'prod_3',
    type: 'phone',
    phoneType: 'iPhone 13',
    ram: '4GB',
    storage: '128GB',
    condition: 'Good',
    price: 65000,
    stockQuantity: 5,
    exchangeEnabled: true,
    description: 'Midnight color. Good condition, all features working.',
    images: [{ storageId: 'st_3', url: 'https://placehold.co/300x300/2e1a1a/ffffff?text=iPhone+13', order: 1 }],
    createdAt: now - 14 * day,
    createdBy: '123456789',
    updatedAt: now - 3 * day,
    updatedBy: '123456789',
  },
  {
    _id: 'prod_4',
    type: 'phone',
    phoneType: 'Camon 20 Pro',
    ram: '8GB',
    storage: '256GB',
    condition: 'Excellent',
    price: 28000,
    stockQuantity: 1,
    exchangeEnabled: false,
    description: 'Dark Welkin. Brand new sealed box.',
    images: [{ storageId: 'st_4', url: 'https://placehold.co/300x300/1a1a1a/ffffff?text=Camon+20', order: 1 }],
    createdAt: now - 5 * day,
    createdBy: '123456789',
    updatedAt: now - 5 * day,
    updatedBy: '123456789',
  },
  {
    _id: 'prod_5',
    type: 'phone',
    phoneType: 'Redmi Note 12 Pro',
    ram: '8GB',
    storage: '256GB',
    condition: 'Excellent',
    price: 32000,
    stockQuantity: 4,
    exchangeEnabled: true,
    description: 'Midnight Black. Full accessories included.',
    images: [{ storageId: 'st_5', url: 'https://placehold.co/300x300/2e2e1a/ffffff?text=Redmi+Note+12', order: 1 }],
    createdAt: now - 8 * day,
    createdBy: '123456789',
    updatedAt: now - 8 * day,
    updatedBy: '123456789',
  },
  {
    _id: 'prod_6',
    type: 'phone',
    phoneType: 'Galaxy A54',
    ram: '8GB',
    storage: '128GB',
    condition: 'Fair',
    price: 22000,
    stockQuantity: 0,
    exchangeEnabled: false,
    description: 'Awesome Graphite. Screen has minor scratches.',
    images: [{ storageId: 'st_6', url: 'https://placehold.co/300x300/1a2e2e/ffffff?text=Galaxy+A54', order: 1 }],
    createdAt: now - 20 * day,
    createdBy: '123456789',
    updatedAt: now - 4 * day,
    updatedBy: '123456789',
  },
  {
    _id: 'prod_7',
    type: 'accessory',
    phoneType: 'AirPods Pro 2nd Gen',
    price: 18000,
    stockQuantity: 6,
    exchangeEnabled: false,
    description: 'Apple AirPods Pro 2nd generation. Active noise cancellation.',
    images: [{ storageId: 'st_7', url: 'https://placehold.co/300x300/2e2e2e/ffffff?text=AirPods+Pro', order: 1 }],
    createdAt: now - 12 * day,
    createdBy: '123456789',
    updatedAt: now - 12 * day,
    updatedBy: '123456789',
  },
  {
    _id: 'prod_8',
    type: 'accessory',
    phoneType: 'Galaxy Buds2 Pro',
    price: 12000,
    stockQuantity: 2,
    exchangeEnabled: false,
    description: 'Bora Purple. Hi-Fi sound with ANC.',
    images: [{ storageId: 'st_8', url: 'https://placehold.co/300x300/1a1a2e/ffffff?text=Galaxy+Buds2', order: 1 }],
    createdAt: now - 9 * day,
    createdBy: '123456789',
    updatedAt: now - 9 * day,
    updatedBy: '123456789',
  },
  {
    _id: 'prod_9',
    type: 'phone',
    phoneType: 'Note 30 Pro',
    ram: '8GB',
    storage: '256GB',
    condition: 'Excellent',
    price: 25000,
    stockQuantity: 3,
    exchangeEnabled: true,
    description: 'Mirror Black. 68W fast charging.',
    images: [{ storageId: 'st_9', url: 'https://placehold.co/300x300/2e1a2e/ffffff?text=Note+30+Pro', order: 1 }],
    createdAt: now - 6 * day,
    createdBy: '123456789',
    updatedAt: now - 6 * day,
    updatedBy: '123456789',
  },
  {
    _id: 'prod_10',
    type: 'phone',
    phoneType: 'Reno 10 Pro',
    ram: '12GB',
    storage: '256GB',
    condition: 'Good',
    price: 42000,
    stockQuantity: 2,
    exchangeEnabled: true,
    description: 'Glossy Purple. 80W SuperVOOC charging.',
    images: [{ storageId: 'st_10', url: 'https://placehold.co/300x300/1a2e1a/ffffff?text=Reno+10+Pro', order: 1 }],
    createdAt: now - 11 * day,
    createdBy: '123456789',
    updatedAt: now - 11 * day,
    updatedBy: '123456789',
  },
];

// ---- THREADS ----

export const mockThreads: Thread[] = [
  {
    _id: 'thread_1',
    telegramId: 'cust_1001',
    customerFirstName: 'Abebe',
    customerLastName: 'Kebede',
    customerUsername: 'abebe_k',
    status: 'new',
    unreadCount: 3,
    lastMessageAt: now - 1 * hour,
    lastMessagePreview: 'I have a budget of around 80,000 ETB, can we negotiate?',
    lastCustomerMessageAt: now - 1 * hour,
    hasCustomerMessaged: true,
    hasAdminReplied: false,
    lastCustomerMessageHasBudgetKeyword: true,
    createdAt: now - 2 * hour,
    updatedAt: now - 1 * hour,
    category: 'hot',
  },
  {
    _id: 'thread_2',
    telegramId: 'cust_1002',
    customerFirstName: 'Tigist',
    customerLastName: 'Haile',
    customerUsername: 'tigist_h',
    status: 'seen',
    unreadCount: 0,
    lastMessageAt: now - 3 * hour,
    lastMessagePreview: 'Okay, I will come tomorrow morning.',
    lastCustomerMessageAt: now - 3 * hour,
    hasCustomerMessaged: true,
    hasAdminReplied: true,
    lastCustomerMessageHasBudgetKeyword: false,
    createdAt: now - 5 * hour,
    updatedAt: now - 3 * hour,
    category: 'warm',
  },
  {
    _id: 'thread_3',
    telegramId: 'cust_1003',
    customerFirstName: 'Dawit',
    customerLastName: 'Bekele',
    status: 'new',
    unreadCount: 1,
    lastMessageAt: now - 30 * hour,
    lastMessagePreview: 'Exchange request submitted.',
    hasCustomerMessaged: false,
    hasAdminReplied: false,
    lastCustomerMessageHasBudgetKeyword: false,
    createdAt: now - 30 * hour,
    updatedAt: now - 30 * hour,
    category: 'cold',
  },
  {
    _id: 'thread_4',
    telegramId: 'cust_1004',
    customerFirstName: 'Sara',
    customerLastName: 'Tesfaye',
    customerUsername: 'sara_t',
    status: 'seen',
    unreadCount: 2,
    lastMessageAt: now - 1.5 * hour,
    lastMessagePreview: 'When can I pick up the phone?',
    lastCustomerMessageAt: now - 1.5 * hour,
    hasCustomerMessaged: true,
    hasAdminReplied: true,
    lastCustomerMessageHasBudgetKeyword: false,
    createdAt: now - 6 * hour,
    updatedAt: now - 1.5 * hour,
    category: 'hot',
  },
  {
    _id: 'thread_5',
    telegramId: 'cust_1005',
    customerFirstName: 'Yonas',
    customerLastName: 'Girma',
    status: 'done',
    unreadCount: 0,
    lastMessageAt: now - 2 * day,
    lastMessagePreview: 'Thank you! Exchange completed.',
    hasCustomerMessaged: true,
    hasAdminReplied: true,
    lastCustomerMessageHasBudgetKeyword: false,
    createdAt: now - 5 * day,
    updatedAt: now - 2 * day,
    category: 'cold',
  },
  {
    _id: 'thread_6',
    telegramId: 'cust_1006',
    customerFirstName: 'Meron',
    customerLastName: 'Alemu',
    customerUsername: 'meron_a',
    status: 'new',
    unreadCount: 1,
    lastMessageAt: now - 26 * hour,
    lastMessagePreview: 'I submitted an exchange request.',
    hasCustomerMessaged: false,
    hasAdminReplied: false,
    lastCustomerMessageHasBudgetKeyword: false,
    createdAt: now - 26 * hour,
    updatedAt: now - 26 * hour,
    category: 'cold',
  },
];

// ---- MESSAGES ----

export const mockMessages: Message[] = [
  {
    _id: 'msg_1',
    threadId: 'thread_1',
    sender: 'customer',
    senderTelegramId: 'cust_1001',
    text: 'Hello, I want to exchange my Samsung S21 for an iPhone 14 Pro.',
    createdAt: now - 2 * hour,
  },
  {
    _id: 'msg_2',
    threadId: 'thread_1',
    sender: 'admin',
    senderTelegramId: '123456789',
    text: 'Hi Abebe! We can help with that. Let me check the value of your S21.',
    createdAt: now - 1.8 * hour,
  },
  {
    _id: 'msg_3',
    threadId: 'thread_1',
    sender: 'customer',
    senderTelegramId: 'cust_1001',
    text: 'Great! I have a budget of around 80,000 ETB, can we negotiate?',
    createdAt: now - 1 * hour,
  },
  {
    _id: 'msg_4',
    threadId: 'thread_2',
    sender: 'customer',
    senderTelegramId: 'cust_1002',
    text: 'I submitted an exchange for iPhone 13. When can I come?',
    createdAt: now - 5 * hour,
  },
  {
    _id: 'msg_5',
    threadId: 'thread_2',
    sender: 'admin',
    senderTelegramId: '123456789',
    text: 'Your Samsung Galaxy A52 is worth 18,000 ETB.\niPhone 13 costs 65,000 ETB.\nYou pay 47,000 ETB.\n\nWhen can you meet at PO Box 014?',
    createdAt: now - 4 * hour,
    exchangeId: 'exch_2',
  },
  {
    _id: 'msg_6',
    threadId: 'thread_2',
    sender: 'customer',
    senderTelegramId: 'cust_1002',
    text: 'Okay, I will come tomorrow morning.',
    createdAt: now - 3 * hour,
  },
  {
    _id: 'msg_7',
    threadId: 'thread_4',
    sender: 'customer',
    senderTelegramId: 'cust_1004',
    text: 'Hi, I want to exchange my Tecno Camon 19 for Galaxy S23 Ultra.',
    createdAt: now - 6 * hour,
  },
  {
    _id: 'msg_8',
    threadId: 'thread_4',
    sender: 'admin',
    senderTelegramId: '123456789',
    text: 'Hello Sara! We received your exchange request. We will review it shortly.',
    createdAt: now - 5 * hour,
  },
  {
    _id: 'msg_9',
    threadId: 'thread_4',
    sender: 'customer',
    senderTelegramId: 'cust_1004',
    text: 'When can I pick up the phone?',
    createdAt: now - 1.5 * hour,
  },
];

// ---- EXCHANGES ----

export const mockExchanges: Exchange[] = [
  {
    _id: 'exch_1',
    telegramId: 'cust_1001',
    threadId: 'thread_1',
    desiredPhoneId: 'prod_1',
    tradeInBrand: 'Samsung',
    tradeInModel: 'Galaxy S21',
    tradeInStorage: '128GB',
    tradeInRam: '8GB',
    tradeInCondition: 'Good',
    customerNotes: 'I have a budget of around 80,000 ETB',
    budgetMentionedInSubmission: true,
    desiredPhonePrice: 95000,
    calculatedTradeInValue: 35000,
    calculatedDifference: 60000,
    finalTradeInValue: 35000,
    finalDifference: 60000,
    priorityValueETB: 35000,
    status: 'Pending',
    clickedContinue: true,
    createdAt: now - 2 * hour,
    updatedAt: now - 2 * hour,
    category: 'hot',
    desiredPhone: undefined,
  },
  {
    _id: 'exch_2',
    telegramId: 'cust_1002',
    threadId: 'thread_2',
    desiredPhoneId: 'prod_3',
    tradeInBrand: 'Samsung',
    tradeInModel: 'Galaxy A52',
    tradeInStorage: '128GB',
    tradeInRam: '6GB',
    tradeInCondition: 'Good',
    budgetMentionedInSubmission: false,
    desiredPhonePrice: 65000,
    calculatedTradeInValue: 18000,
    calculatedDifference: 47000,
    finalTradeInValue: 18000,
    finalDifference: 47000,
    priorityValueETB: 18000,
    status: 'Quoted',
    clickedContinue: true,
    quotedAt: now - 4 * hour,
    quotedBy: '123456789',
    quoteMessageId: 'msg_5',
    createdAt: now - 5 * hour,
    updatedAt: now - 4 * hour,
    category: 'warm',
  },
  {
    _id: 'exch_3',
    telegramId: 'cust_1003',
    threadId: 'thread_3',
    desiredPhoneId: 'prod_2',
    tradeInBrand: 'Tecno',
    tradeInModel: 'Camon 18',
    tradeInStorage: '128GB',
    tradeInRam: '6GB',
    tradeInCondition: 'Fair',
    budgetMentionedInSubmission: false,
    desiredPhonePrice: 85000,
    calculatedTradeInValue: 8000,
    calculatedDifference: 77000,
    finalTradeInValue: 8000,
    finalDifference: 77000,
    priorityValueETB: 8000,
    status: 'Pending',
    clickedContinue: false,
    createdAt: now - 30 * hour,
    updatedAt: now - 30 * hour,
    category: 'cold',
  },
  {
    _id: 'exch_4',
    telegramId: 'cust_1004',
    threadId: 'thread_4',
    desiredPhoneId: 'prod_2',
    tradeInBrand: 'Tecno',
    tradeInModel: 'Camon 19',
    tradeInStorage: '128GB',
    tradeInRam: '8GB',
    tradeInCondition: 'Good',
    budgetMentionedInSubmission: false,
    desiredPhonePrice: 85000,
    calculatedTradeInValue: 12000,
    calculatedDifference: 73000,
    finalTradeInValue: 12000,
    finalDifference: 73000,
    priorityValueETB: 12000,
    status: 'Pending',
    clickedContinue: true,
    createdAt: now - 6 * hour,
    updatedAt: now - 6 * hour,
    category: 'hot',
  },
  {
    _id: 'exch_5',
    telegramId: 'cust_1005',
    threadId: 'thread_5',
    desiredPhoneId: 'prod_1',
    tradeInBrand: 'iPhone',
    tradeInModel: 'iPhone 12',
    tradeInStorage: '128GB',
    tradeInRam: '4GB',
    tradeInCondition: 'Good',
    budgetMentionedInSubmission: false,
    desiredPhonePrice: 95000,
    calculatedTradeInValue: 55000,
    calculatedDifference: 40000,
    finalTradeInValue: 55000,
    finalDifference: 40000,
    priorityValueETB: 55000,
    status: 'Completed',
    clickedContinue: true,
    quotedAt: now - 4 * day,
    quotedBy: '123456789',
    createdAt: now - 5 * day,
    updatedAt: now - 2 * day,
    completedAt: now - 2 * day,
    completedBy: '123456789',
    category: 'cold',
  },
  {
    _id: 'exch_6',
    telegramId: 'cust_1006',
    threadId: 'thread_6',
    desiredPhoneId: 'prod_5',
    tradeInBrand: 'Infinix',
    tradeInModel: 'Hot 20i',
    tradeInStorage: '64GB',
    tradeInRam: '4GB',
    tradeInCondition: 'Fair',
    budgetMentionedInSubmission: false,
    desiredPhonePrice: 32000,
    calculatedTradeInValue: 5000,
    calculatedDifference: 27000,
    finalTradeInValue: 5000,
    finalDifference: 27000,
    priorityValueETB: 5000,
    status: 'Pending',
    clickedContinue: false,
    createdAt: now - 26 * hour,
    updatedAt: now - 26 * hour,
    category: 'cold',
  },
];

// ---- INVENTORY EVENTS ----

export const mockInventoryEvents: InventoryEvent[] = [
  {
    _id: 'inv_1',
    productId: 'prod_1',
    oldQty: 4,
    newQty: 3,
    editedBy: '123456789',
    reason: 'Exchange completed',
    exchangeId: 'exch_5',
    timestamp: now - 2 * day,
  },
  {
    _id: 'inv_2',
    productId: 'prod_6',
    oldQty: 1,
    newQty: 0,
    editedBy: '123456789',
    reason: 'Manual adjustment',
    timestamp: now - 4 * day,
  },
  {
    _id: 'inv_3',
    productId: 'prod_4',
    oldQty: 2,
    newQty: 1,
    editedBy: '123456789',
    reason: 'Manual adjustment',
    timestamp: now - 1 * day,
  },
];

// ---- DASHBOARD STATS ----

export const mockDashboardStats: DashboardStats = {
  newExchangesToday: 2,
  newMessagesToday: 5,
  openThreads: 4,
  lowStockCount: 4, // prod_2, prod_4, prod_8, prod_10 have stock <= 2
};

// ---- RECENT ACTIVITY ----

export const mockRecentActivity: RecentActivity[] = [
  {
    id: 'act_1',
    type: 'message_sent',
    title: 'New message from Abebe Kebede',
    subtitle: 'I have a budget of around 80,000 ETB...',
    timestamp: now - 1 * hour,
  },
  {
    id: 'act_2',
    type: 'exchange_submitted',
    title: 'Exchange submitted by Sara Tesfaye',
    subtitle: 'Tecno Camon 19 → Galaxy S23 Ultra',
    timestamp: now - 6 * hour,
  },
  {
    id: 'act_3',
    type: 'exchange_submitted',
    title: 'Exchange submitted by Abebe Kebede',
    subtitle: 'Samsung Galaxy S21 → iPhone 14 Pro',
    timestamp: now - 2 * hour,
  },
  {
    id: 'act_4',
    type: 'exchange_quoted',
    title: 'Quote sent to Tigist Haile',
    subtitle: 'Samsung Galaxy A52 → iPhone 13 · Pay 47,000 ETB',
    timestamp: now - 4 * hour,
  },
  {
    id: 'act_5',
    type: 'stock_changed',
    title: 'Stock updated: Tecno Camon 20 Pro',
    subtitle: '2 → 1 unit (Manual adjustment)',
    timestamp: now - 1 * day,
  },
  {
    id: 'act_6',
    type: 'exchange_completed',
    title: 'Exchange completed: Yonas Girma',
    subtitle: 'iPhone 12 → iPhone 14 Pro · 40,000 ETB',
    timestamp: now - 2 * day,
  },
  {
    id: 'act_7',
    type: 'product_added',
    title: 'Product added: Oppo Reno 10 Pro',
    subtitle: '42,000 ETB · 2 units',
    timestamp: now - 11 * day,
  },
];
